#!/bin/bash
# PreToolUse guard: deny edits to generated/managed files and point to the right command instead.
# Parses the hook payload with node (always present in this repo) rather than jq.
file=$(node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(JSON.parse(d).tool_input?.file_path??"")}catch{}})')
case "$file" in
	*routeTree.gen.ts)
		reason="src/routeTree.gen.ts is generated — it is regenerated by 'pnpm dev' (while running) or 'pnpm build'. Add or rename files in src/routes/ instead of editing it." ;;
	*pnpm-lock.yaml)
		reason="pnpm-lock.yaml is managed by pnpm — run 'pnpm add <pkg>' or 'pnpm install' instead of editing." ;;
	*)
		exit 0 ;;
esac
node -e 'console.log(JSON.stringify({hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:process.argv[1]}}))' "$reason"
